name: Generally
description: File a generally issue about cppwinrt
title: "Enhancement: "
labels: [enhancement]
assignees: []
body:
  - type: markdown
    attributes:
      value: "Thank you for filing a generally issue!
  - type: textarea
  - type: markdown
    attributes:
      value: "Thank you! ©️➕➕"
